Repository Quento-Solutions/Quento, pull requests merged in 2020-08, with the labels that each got.

#45 chore: remove coverage folder
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/components/Card.vue.html
  coverage/lcov-report/components/FooterCard.vue.html
  coverage/lcov-report/components/NotesCard.vue.html
  coverage/lcov-report/components/NotesSidebar.vue.html
  coverage/lcov-report/components/Sidebar.vue.html
  coverage/lcov-report/components/VxCard.vue.html
  coverage/lcov-report/components/index.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/layouts/auth.vue.html
  coverage/lcov-report/layouts/index.html
  coverage/lcov-report/layouts/main.vue.html
  coverage/lcov-report/pages/Home.vue.html
  coverage/lcov-report/pages/Suggestions.vue.html
  coverage/lcov-report/pages/auth.vue.html
  coverage/lcov-report/pages/auth/Login.vue.html
  coverage/lcov-report/pages/auth/SignUp.vue.html
  coverage/lcov-report/pages/auth/index.html
  coverage/lcov-report/pages/index.html
  coverage/lcov-report/pages/index.vue.html
  coverage/lcov-report/pages/notes.vue.html
  coverage/lcov-report/pages/notes/_id.vue.html
  coverage/lcov-report/pages/notes/index.html
  coverage/lcov-report/pages/notes/index.vue.html
  coverage/lcov-report/plugins/aos.ts.html
  coverage/lcov-report/plugins/client_runtime.ts.html
  coverage/lcov-report/plugins/fireauth.ts.html
  coverage/lcov-report/plugins/firebase.ts.html
  coverage/lcov-report/plugins/firebaseStorage.ts.html
  coverage/lcov-report/plugins/firestore.ts.html
  coverage/lcov-report/plugins/globalComponents.ts.html
  coverage/lcov-report/plugins/index.html
  coverage/lcov-report/plugins/vue-video-player.ts.html
  coverage/lcov-report/plugins/vuesax.ts.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/store/auth.ts.html
  coverage/lcov-report/store/index.html
  coverage/lcov-report/store/index.ts.html
  coverage/lcov-report/store/navigation.ts.html
  coverage/lcov-report/store/notes.ts.html
  coverage/lcov-report/store/suggestions.ts.html
  coverage/lcov-report/store/window.ts.html
  coverage/lcov.info
Labels: chore

#48 Subject select component
  components/NotesSidebar.vue
  components/SubjectsDropdown.vue
  screens/UserInformationModal.vue
  types/subjects.ts
Labels: refactor

#228 Editable profile page
  assets/scss/main.scss
  components/TopNav.vue
  middleware/router-auth.ts
  mixins/UserMixin.ts
  pages/questions/_id.vue
  pages/user/edit.vue
  pages/user/profile.vue
  plugins/firebaseFunctions.ts
  screens/UserInformationModal.vue
  screens/notes/PostNotesModal.vue
  screens/questions/PostQuestionModal.vue
  store/auth.ts
  store/questions.ts
  store/suggestions.ts
  types/subjects.ts
  types/user.ts
Labels: enhancement, feature, fix

#239 feat : notification bar
  components/Sidebar.vue
  components/TopNav.vue
  layouts/main.vue
  nuxt.config.ts
  pages/notifications.vue
  pages/notifications/_id.vue
  plugins/globalComponents.ts
  plugins/messyPlugins.js
  store/newsletters.ts
  store/notes.ts
  store/notifications.ts
  store/suggestions.ts
  types/firebaseTypes.ts
  types/notifications.ts
  utils/store-accessor.ts
Labels: feature

#256 feat: add phy ed as a favouritable subject
  types/subjects.ts
Labels: chore

#252 fix: md list rendering on chromium
  assets/scss/components/notes_md.scss
  pages/newsletters.vue
Labels: bug

#251 fix: add firebase sw to gitignore
  .gitignore
  static/firebase-auth-sw.js
Labels: chore
