Repository Quento-Solutions/Quento, pull requests merged in 2020-09, with the labels that each got.

#272 Added Simple Sitemap to Documentation
  README.md
Labels: documentation

#295 Added Folders to README
  README.md
Labels: chore

#312 feat: personalized notes feed without int firebase reads
  pages/notes/index.vue
  store/moduleTemplate.ts
  store/notes.ts
  store/questions.ts
  store/userGuide.ts
  types/env.utils.ts
  types/notes.ts
  types/user.ts
  utils/time.ts
Labels: feature

#318 feat: personalized questions feed
  pages/questions/index.vue
  store/questions.ts
Labels: enhancement

#320 feat: combined notes and questions personalized feed
  components/QuestionCard.vue
  pages/Home.vue
  store/feeds.ts
Labels: feature

#335 After launch issues fixes
  README.md
  components/NotesCard.vue
  pages/notes/_id.vue
  store/notes.ts
  types/notes.ts
  types/schools.ts
  types/subjects.ts
  types/suggestions.ts
  utils/time.ts
Labels: bug
